Shop/ServiceHost/Areas/Admin/Pages/Discounts/ColleagueDiscount/Index.cshtml.cs
using DiscountManagement.Application.Contract.ColleagueDiscount;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contracts.Product;
using System.Collections.Generic;

namespace ServiceHost.Areas.Admin.Pages.Discounts.ColleagueDiscount
{
    public class IndexModel : PageModel
    {
        [TempData] public string message { get; set; }
        public ColleagueDiscountSearchModel SearchModel;
        public List<ColleagueDiscountViewModel> colleagueDiscounts;
        public SelectList Products;

        private readonly IProductApplication _ProductApplication;
        private readonly IColleagueDiscountApplication _colleagueDiscountApplication;

        public IndexModel(IProductApplication productApplication, IColleagueDiscountApplication colleagueDiscountApplication)
        {
            _ProductApplication=productApplication;
            _colleagueDiscountApplication=colleagueDiscountApplication;

        }

        public void OnGet(ColleagueDiscountSearchModel searchModel)
        {
            Products=new SelectList(_ProductApplication.GetProducts(), "Id", "Name");
            colleagueDiscounts= _colleagueDiscountApplication.Search(searchModel);
        }

        public IActionResult OnGetCreate()
        {
            var command = new DefineColleagueDiscount
            {
                Products=_ProductApplication.GetProducts()
            };
            return Partial("./Create", command);
        }

        public JsonResult OnPostCreate(DefineColleagueDiscount command)
        {
            var result = _colleagueDiscountApplication.Define(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var ColleagueDiscount = _colleagueDiscountApplication.GetDetails(id);
            ColleagueDiscount.Products=_ProductApplication.GetProducts();
            return Partial("Edit", ColleagueDiscount);
        }

        public JsonResult OnPostEdit(EditColleagueDiscount command)
        {
            var result = _colleagueDiscountApplication.Edit(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetRemove(long id)
        {
            var result = _colleagueDiscountApplication.Remove(id);
            if (result.IsSuccedded)
                return RedirectToPage("./Index");

            message= result.Message;
            return RedirectToPage("./Index");


        }
        public IActionResult OnGetRestore(long id)
        {
            var result = _colleagueDiscountApplication.Restore(id);
            if (result.IsSuccedded)
                return RedirectToPage("./Index");

            message= result.Message;
            return RedirectToPage("./Index");

        }

    }
}

Shop/ServiceHost/Areas/Admin/Pages/Discounts/CustomerDiscount/Index.cshtml.cs
using DiscountManagement.Application.Contract.CustomerDiscount;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ShopManagement.Application.Contracts.Product;
using System.Collections.Generic;

namespace ServiceHost.Areas.Admin.Pages.Discounts.CustomerDiscount
{
    public class IndexModel : PageModel
    {
        [TempData] public string message { get; set; }
        public CustomerDiscountSearchModel SearchModel;
        public List<CustomerDiscountViewModel> CustomerDiscounts;
        public SelectList Products;

        private readonly IProductApplication _ProductApplication;
        private readonly ICustomerDiscountApplication _CustomerDiscountApplication;

        public IndexModel(IProductApplication productApplication, ICustomerDiscountApplication CustomerDiscountApplication)
        {
            _ProductApplication=productApplication;
            _CustomerDiscountApplication=CustomerDiscountApplication;

        }

        public void OnGet(CustomerDiscountSearchModel searchModel)
        {
            Products=new SelectList(_ProductApplication.GetProducts(), "Id", "Name");
            CustomerDiscounts= _CustomerDiscountApplication.Search(searchModel);
        }

        public IActionResult OnGetCreate()
        {
            var command = new DefineCustomerDiscount
            {
                Products=_ProductApplication.GetProducts()
            };
            return Partial("./Create", command);
        }

        public JsonResult OnPostCreate(DefineCustomerDiscount command)
        {
            var result = _CustomerDiscountApplication.Define(command);
            return new JsonResult(result);
        }

        public IActionResult OnGetEdit(long id)
        {
            var CustomerDiscount = _CustomerDiscountApplication.GetDetails(id);
            CustomerDiscount.Products=_ProductApplication.GetProducts();
            return Partial("Edit", CustomerDiscount);
        }

        public JsonResult OnPostEdit(EditCustomerDiscount command)
        {
            var result = _CustomerDiscountApplication.Edit(command);
            return new JsonResult(result);
        }
    }
}

Shop/ServiceHost/Areas/Admin/Pages/Discounts/ColleagueDiscount/Create.cshtml
@model DiscountManagement.Application.Contract.ColleagueDiscount.DefineColleagueDiscount
@{
}

<div class="modal-header alert-success m-2">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title ">تعریف تخفیف همکار جدید </h4>
</div>

<form asp-page="./Index" asp-page-handler="Create"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">

        <div class="row">

            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="Reason" class="control-label">عنوان تخفیف</label>
                        <input type="text" class="form-control" asp-for="Reason" accept="image/*">
                        <span asp-validation-for="Reason" class="error"></span>
                    </div>
                </div>
            </div>

            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="ProductId" class="control-label">انتخاب محصول   </label>
                    <select class="form-control" asp-for="ProductId" asp-items='new SelectList(Model.Products,"Id", "Name")'>
                        <option value="0">انتخاب محصول  </option>
                    </select>
                    <span asp-validation-for="ProductId" class="error"></span>
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="DiscountRate" class="control-label">درصد تخفیف </label>
                    <input type="text" class="form-control" asp-for="DiscountRate">
                    <span asp-validation-for="DiscountRate" class="error"></span>
                </div>
            </div>
        </div>


        <div class="modal-footer">
            <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
            <button type="submit" class="btn btn-success waves-effect waves-light">تعریف </button>
        </div>
    </div>
</form>

Shop/ServiceHost/Areas/Admin/Pages/Discounts/ColleagueDiscount/Edit.cshtml
@model DiscountManagement.Application.Contract.ColleagueDiscount.EditColleagueDiscount
@{
}

<div class="modal-header alert-success m-2">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h4 class="modal-title bg-primary">ویرایش تخفیف همکار :<span class="text-primary"> </span> </h4>
</div>

<form asp-page="./Index" asp-page-handler="Edit"
      method="post"
      data-ajax="true"
      data-callback=""
      data-action="Refresh"
      enctype="multipart/form-data">
    <div class="modal-body">

        <div class="row">

            <div class="row">
                <div class="col-md-12">
                    <div class="form-group">
                        <label asp-for="Reason" class="control-label">عنوان تخفیف</label>
                        <input type="text" class="form-control" asp-for="Reason" accept="image/*">
                        <span asp-validation-for="Reason" class="error"></span>
                    </div>
                </div>
            </div>

            <div class="col-md-12">
                <div class="form-group">
                    <label asp-for="ProductId" class="control-label">انتخاب محصول   </label>
                    <select class="form-control" asp-for="ProductId" asp-items='new SelectList(Model.Products,"Id", "Name")'>
                        <option value="0">انتخاب محصول  </option>
                    </select>
                    <span asp-validation-for="ProductId" class="error"></span>
                </div>
            </div>

        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="form-group">
                    <label asp-for="DiscountRate" class="control-label">درصد تخفیف </label>
                    <input type="text" class="form-control" asp-for="DiscountRate">
                    <span asp-validation-for="DiscountRate" class="error"></span>
                </div>
            </div>
        </div>

      
        <input type="hidden" asp-for="@Model.Id" value="@Model.Id" />

        <div class="modal-footer">
            <button type="button" class="btn btn-default waves-effect" data-dismiss="modal">بستن</button>
            <button type="submit" class="btn btn-success waves-effect waves-light">تعریف </button>
        </div>
    </div>
</form>

Shop/ServiceHost/Areas/Admin/Pages/Discounts/ColleagueDiscount/Index.cshtml
@page
@model ServiceHost.Areas.Admin.Pages.Discounts.ColleagueDiscount.IndexModel
@{
}

@{
    Layout = "Shared/_AdminLayout";
    ViewData["title"] = "مدیریت تخفیفات همکاران";
}

<div class="row">
    <div class="col-sm-12">
        <h4 class="page-title pull-right">@ViewData["title"]</h4>
        <p class="pull-left">
            <a class="btn btn-success btn-lg" href="#showmodal=@Url.Page("./index","Create")">تعریف تخفیف همکار </a>
        </p>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> جستجو در تخفیفات همکاران </h3>
            </div>
            <div class="panel-body">
                <form class="form-inline" role="form" method="get">
                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.Reason"></label>
                        <input class="form-control" asp-for="SearchModel.Reason" placeholder="نام محصول">
                    </div>

                    <div class="form-group">
                        <label class="sr-only" asp-for="SearchModel.ProductId"></label>
                        <select class="form-control" asp-for="SearchModel.ProductId" asp-items="Model.Products">
                            <option value="0"> انتخاب محصول  </option>
                        </select>
                    </div>
                    <button type="submit" class="btn btn-success waves-effect waves-light m-l-10">جستجو</button>
                    <a class="btn btn-primary waves-effect waves-light m-l-10" asp-page="./Index">مشاهده همه</a>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row" id="ProductCategoriesDiv">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">لیست تخفیفات همکاران | « @Model.colleagueDiscounts.Count » </h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <table id="datatable" class="table table-striped table-bordered">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>محصول</th>
                                    <th>درصد تخفیف</th>
                                    <th>علت تخفیف</th>
                                    <th>وصعیت</th>
                                    <th>تاریخ ایجاد </th>
                                    <th>عملیات</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.colleagueDiscounts)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>@item.Product</td>
                                        <td>@item.DiscountRate</td>
                                        <td>@item.Reason</td>
                                        <td>
                                            @if (item.IsRemoved)
                                            {
                                                <i class="fa fa-2x fa-remove text-danger"></i>
                                            }
                                            else
                                            {
                                                <i class="fa fa-2x fa-check text-success"></i>
                                            }
                                        </td>
                                        <td>@item.CreationDate</td>
                                        <td>
                                            <a class="btn btn-warning btn-custom waves-effect waves-light pull-right m-rl-5"
                                           href="#showmodal=@Url.Page("./Index", "Edit", new { id = item.Id})">
                                                <i class="fa fa-edit"></i> ویرایش
                                            </a>

                                            @if (item.IsRemoved)
                                            {
                                                <a class="btn btn-success btn-custom waves-effect waves-light pull-right m-rl-5"
                                           asp-page="./Index" asp-page-handler="Restore" asp-route-id="@item.Id">
                                                    <i class="fa fa-battery-empty" aria-hidden="true"></i>  فعال سازی !
                                                </a>
                                            }
                                            else
                                            {
                                                <a class="btn btn-danger btn-custom waves-effect waves-light pull-right m-rl-5"
                                           asp-page="./Index" asp-page-handler="Remove" asp-route-id="@item.Id">
                                                    <i class="fa fa-battery-full" aria-hidden="true"></i>  غیر فعال سازی !
                                                </a>
                                            }

                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script src="~/adminTheme/assets/datatables/jquery.dataTables.min.js"></script>
    <script src="~/adminTheme/assets/datatables/dataTables.bootstrap.js"></script>
}